[package]
name = "etcdrs"
version.workspace = true
edition.workspace = true

[dependencies]
async-stream.workspace = true
futures-core.workspace = true
prost.workspace = true
prost-types.workspace = true
tokio = { workspace = true, features = ["sync"] }
tonic.workspace = true
tonic-prost.workspace = true

[dev-dependencies]
futures.workspace = true
tokio = { workspace = true, default-features = false, features = ["macros", "rt"] }

[build-dependencies]
protoc-bin-vendored = { workspace = true, optional = true }
tonic-prost-build = { workspace = true, optional = true }

[features]
default = []
generate = ["dep:protoc-bin-vendored", "dep:tonic-prost-build"]
nightly-async-iterator = []  # enable `std::async_iter` features
