// This file is @generated by prost-build.
pub(crate) mod authpb {
    #![allow(unused)]
    include!("authpb.rs");
}
pub(crate) mod etcdserverpb {
    #![allow(unused)]
    include!("etcdserverpb.rs");
}
pub(crate) mod google {
    #![allow(unused)]
    pub(crate) mod api {
        include!("google.api.rs");
    }
}
pub(crate) mod grpc {
    #![allow(unused)]
    pub(crate) mod gateway {
        pub(crate) mod protoc_gen_openapiv2 {
            pub(crate) mod options {
                include!("grpc.gateway.protoc_gen_openapiv2.options.rs");
            }
        }
    }
}
pub(crate) mod mvccpb {
    #![allow(unused)]
    include!("mvccpb.rs");
}
