// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub(crate) struct UserAddOptions {
    #[prost(bool, tag = "1")]
    pub(crate) no_password: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub(crate) struct User {
    #[prost(bytes = "vec", tag = "1")]
    pub(crate) name: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub(crate) password: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag = "3")]
    pub(crate) roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub(crate) options: ::core::option::Option<UserAddOptions>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub(crate) struct Permission {
    #[prost(enumeration = "permission::Type", tag = "1")]
    pub(crate) perm_type: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub(crate) key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub(crate) range_end: ::prost::alloc::vec::Vec<u8>,
}
pub(crate) mod permission {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub(crate) enum Type {
        Read = 0,
        Write = 1,
        Readwrite = 2,
    }
    impl Type {
        pub(crate) fn as_str_name(&self) -> &'static str {
            match self {
                Self::Read => "READ",
                Self::Write => "WRITE",
                Self::Readwrite => "READWRITE",
            }
        }
        pub(crate) fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "READ" => Some(Self::Read),
                "WRITE" => Some(Self::Write),
                "READWRITE" => Some(Self::Readwrite),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub(crate) struct Role {
    #[prost(bytes = "vec", tag = "1")]
    pub(crate) name: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "2")]
    pub(crate) key_permission: ::prost::alloc::vec::Vec<Permission>,
}
