// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub(crate) struct Http {
    #[prost(message, repeated, tag = "1")]
    pub(crate) rules: ::prost::alloc::vec::Vec<HttpRule>,
    #[prost(bool, tag = "2")]
    pub(crate) fully_decode_reserved_expansion: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub(crate) struct HttpRule {
    #[prost(string, tag = "1")]
    pub(crate) selector: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub(crate) body: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub(crate) response_body: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "11")]
    pub(crate) additional_bindings: ::prost::alloc::vec::Vec<HttpRule>,
    #[prost(oneof = "http_rule::Pattern", tags = "2, 3, 4, 5, 6, 8")]
    pub(crate) pattern: ::core::option::Option<http_rule::Pattern>,
}
pub(crate) mod http_rule {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub(crate) enum Pattern {
        #[prost(string, tag = "2")]
        Get(::prost::alloc::string::String),
        #[prost(string, tag = "3")]
        Put(::prost::alloc::string::String),
        #[prost(string, tag = "4")]
        Post(::prost::alloc::string::String),
        #[prost(string, tag = "5")]
        Delete(::prost::alloc::string::String),
        #[prost(string, tag = "6")]
        Patch(::prost::alloc::string::String),
        #[prost(message, tag = "8")]
        Custom(super::CustomHttpPattern),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub(crate) struct CustomHttpPattern {
    #[prost(string, tag = "1")]
    pub(crate) kind: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub(crate) path: ::prost::alloc::string::String,
}
