// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub(crate) struct KeyValue {
    #[prost(bytes = "bytes", tag = "1")]
    pub(crate) key: ::prost::bytes::Bytes,
    #[prost(int64, tag = "2")]
    pub(crate) create_revision: i64,
    #[prost(int64, tag = "3")]
    pub(crate) mod_revision: i64,
    #[prost(int64, tag = "4")]
    pub(crate) version: i64,
    #[prost(bytes = "bytes", tag = "5")]
    pub(crate) value: ::prost::bytes::Bytes,
    #[prost(int64, tag = "6")]
    pub(crate) lease: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub(crate) struct Event {
    #[prost(enumeration = "event::EventType", tag = "1")]
    pub(crate) r#type: i32,
    #[prost(message, optional, tag = "2")]
    pub(crate) kv: ::core::option::Option<KeyValue>,
    #[prost(message, optional, tag = "3")]
    pub(crate) prev_kv: ::core::option::Option<KeyValue>,
}
pub(crate) mod event {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub(crate) enum EventType {
        Put = 0,
        Delete = 1,
    }
    impl EventType {
        pub(crate) fn as_str_name(&self) -> &'static str {
            match self {
                Self::Put => "PUT",
                Self::Delete => "DELETE",
            }
        }
        pub(crate) fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "PUT" => Some(Self::Put),
                "DELETE" => Some(Self::Delete),
                _ => None,
            }
        }
    }
}
