// This file is @generated by prost-build.
pub mod authpb {
    include!("authpb.rs");
}
pub mod etcdserverpb {
    include!("etcdserverpb.rs");
}
pub mod google {
    pub mod api {
        include!("google.api.rs");
    }
}
pub mod grpc {
    pub mod gateway {
        pub mod protoc_gen_openapiv2 {
            pub mod options {
                include!("grpc.gateway.protoc_gen_openapiv2.options.rs");
            }
        }
    }
}
pub mod mvccpb {
    include!("mvccpb.rs");
}
