[workspace]
members = [
    "etcdrs",
    "etcdrs-test",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
async-stream = "^0.3.5"
fallible-async-iterator = { git = "https://github.com/tgockel/fallible-async-iterator.git", rev = "8eea9c797680af46a5efed7925f1275e7baa9e76", features = ["futures-core"] }
futures-core = "^0.3.30"
prost = "^0.13.1"
prost-types = "^0.13.1"
rand = "^0.8.5"
rstest = "^0.21.0"
tokio = { version = "^1.38.0", default-features = false }
tonic = "^0.12.0"
tonic-build = "^0.12.0"
url = "^2.5.2"

etcdrs = { path = "etcdrs" }
