[package]
name = "etcdrs-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
rstest = ["dep:rstest"]

[dependencies]
etcdrs.workspace = true
etcd-bin-vendored.workspace = true
futures = { workspace = true, default-features = true }
rand = { workspace = true, features = ["std", "std_rng", "thread_rng"] }
rstest = { workspace = true, optional = true, features = ["async-timeout", "crate-name"] }

[dev-dependencies]
etcdrs-test = { path = ".", features = ["rstest"] }
tokio = { workspace = true, default-features = false, features = ["macros", "rt", "time"] }
