[package]
name = "etcdrs-test"
version.workspace = true
edition.workspace = true

[dependencies]
etcdrs.workspace = true
etcd-bin-vendored.workspace = true
futures = { workspace = true, default-features = true }
rand.workspace = true

[dev-dependencies]
rstest.workspace = true
tokio = { workspace = true, default-features = false, features = ["macros", "rt", "time"] }
